version: "2"
linters:
  enable:
    - bodyclose
    - gocyclo
    - misspell
    - revive
    - unconvert
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: exported
          severity: warning
        - name: package-comments
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocyclo
          - revive
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
